### ISSUE TITLE
Crash when using with AOF5 Modpack

### ISSUE THREAD

**Issue by Demsli** [CmdrJane/Fabric-restart#5]
Recieving this crash:
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
	at ru.aiefu.fabricrestart.FabricRestart.readConfiguration(FabricRestart.java:59)
	at ru.aiefu.fabricrestart.FabricRestart.lambda$onInitializeServer$0(FabricRestart.java:36)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:37)
	at net.minecraft.server.MinecraftServer.handler$bof000$beforeSetupServer(MinecraftServer.java:4268)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 7 more

With version 1.4 the mod worked, but for some reason didnt start the server again. So I tried 1.5, but now the server doesnt start at all. Plz help

**Comment by CmdrJane** [comment]
fixed in latest release
